version: "3.7"

services:
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: kegpass
      POSTGRES_USER: kegweight
      POSTGRES_DB: kegweight
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kegweight"]
      interval: 3s
      timeout: 3s
      retries: 3

    
